### ISSUE TITLE
two problems booting deployed grisp

### ISSUE THREAD

**Issue by Rashidwi** [grisp/mix_grisp#10]
Booting on grisp2 gets this far:

> warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfuncti
> on as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running
>  "locale" in your shell) or set the ELIXIR_ERL_OPTIONS="+fnu" environment variable
> Error! elixir:start_iex/0 is not exported.
> 
> Runtime terminating during boot ({undef,[{elixir,start_iex,[],[]},{init,start_it,1,[]},{init,start
> _em,1,[]},{init,do_boot,3,[]}]})
> 
> Crash dump is being written to: erl_crash.dump...done
> 
> 
> fatal extension: source=5, is_internal=0, error=1

I've checked, and double checked my mix.exs and the modified entries in grisp/grisp2/common/deploy/files/grisp.ini.mustache and they all seem to be in accordance with the documentation. 

I have included mix.exs here (rename with .txt so github accepts it). 

[mix.exs.txt](https://github.com/user-attachments/files/16979512/mix.exs.txt)

Anything I can add to help ?

S

**Comment by ziopio** [comment]
I'll try to reproduce using you configuration

**Comment by Rashidwi** [comment]
Hi,

I've retested my set up and found that I had put the  grisp.ini.mustache and wpa_supplicant.conf files in the wrong place. (Despite this they were being found by the install and placed in the root of the sd card)

With this corrected (now in project_root/grisp/grisp2/common/deploy/files) I'm now consistently getting this error on boot:

>...
> [ERL] getcwd: /media/mmcsd-1-0
> [ERL] Starting BEAM
> [ERL] Erlang shell mode
> Runtime terminating during boot (no_or_multiple_root_variables)
> 
> Crash dump is being written to: erl_crash.dump...done
> 
> 
> fatal extension: source=5, is_internal=0, error=1
> 

I've tried both grisp_tools 2.5.0 and 2.6.1 with no difference.  Also I wondered about the :myapp in releases (in mix.exs) I tried changing this to the actual name of the app (as declared in the project) but it doesn't solve or change anything. I've tried rebuilding endless times, deleting ./_build ./deps and mix.lock, re-running mix deps.get and mix deploy, but the problem seems consistent. 

relevant files (as .txt):
[mix.exs.txt](https://github.com/user-attachments/files/16993032/mix.exs.txt)
[grisp.ini.mustache.txt](https://github.com/user-attachments/files/16993040/grisp.ini.mustache.txt)

this is the grisp.ini from the sd card:
[grisp.ini.txt](https://github.com/user-attachments/files/16993112/grisp.ini.txt)

Yes, I have tidied the arguments in grisp.ini.mustache  but it seems to not have made any difference.

What does  _no_or_multiple_root_variables_ mean and what is the likely problem?

Thanks S

**Comment by ziopio** [comment]
`no_or_multiple_root_variables` is triggered in the init.erl module in OTP

https://github.com/erlang/otp/blob/master/erts/preloaded/src/init.erl#L1219

This is usually triggered when the grisp.ini file is missing the flag. This usually means there is an error in the grisp.ini, or the grisp.ini is the wrong one. 

It could happed that the bootloader reads your SD card and starts your Erlang VM,
then the VM needs to mount your SD card again, but if it fails it mounts the embedded eMMC which might have a non compatible grisp.ini

For this reason it would be usefull if you send the whole terminal output, from the bootloader to the crash.

**Comment by ziopio** [comment]
These are the logs I get preceeding the elixir prompt. 
Check what do you get on `Booting with arg`
```
...
[ERL] GRiSP mountpoint from the FDT: /media/mmcsd-1-0/
hub1: <Freescale EHCI root HUB, class 9/0, rev 2.00/1.00, addr 1> on usbus1
[ERL] Reading /media/mmcsd-1-0/grisp.ini
[ERL] Booting with arg: erl.rtems -C multi_time_warp -- -noshell -noinput -mode embedded -home . -pa . -root myapp -bindir myapp/erts-15.0.1/bin -boot myapp/releases/0.1.0/start -boot_var RELEASE_LIB myapp/lib  -config myapp/releases/0.1.0/sys.config -s elixir start_iex -extra --no-halt
[ERL] hostname: grisp-001159
[ERL] Setting up /etc from /media/mmcsd-1-0/etc
[ERL] Copying directory /media/mmcsd-1-0/etc to /etc
[ERL] Copying file /media/mmcsd-1-0/etc/dhcpcd.conf to /etc/dhcpcd.conf
[ERL] Copying file /media/mmcsd-1-0/etc/hosts to /etc/hosts
[ERL] Copying file /media/mmcsd-1-0/etc/resolv.conf to /etc/resolv.conf
[ERL] Starting DHCP
[ERL] mkdir /tmp
info: ffec0: link state changed to DOWN
[ERL] mkdir /tmp/log
[ERL] mkdir /home
[ERL] Setting environment
[ERL] chdir(/media/mmcsd-1-0/)
[ERL] getcwd: /media/mmcsd-1-0
[ERL] Starting BEAM
[ERL] No shell mode
uhub0: 1 port with 1 removable, self powered
uhub1: 1 port with 1 removable, self powered
ugen1.2: <Realtek 802.11n NIC> at usbus1
rtwn0: <Realtek 802.11n NIC, class 0/0, rev 2.00/0.00, addr 2> on usbus1
rtwn0: MAC/BB RTL8188EU, RF 6052 1T1R
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell) or set the ELIXIR_ERL_OPTIONS="+fnu" environment variable
Erlang/OTP 27 [erts-15.0.1] [source] [32-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]

Interactive Elixir (1.16.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
```

I used erlang 27.0.1 and elixis 1.17.2-otp-27, my mix.exs is mostly the same

**Comment by ziopio** [comment]
I can reproduce your error with otp 27.0.1 and elixir 1.17.2-otp-27
```
u[ERL] GRiSP mountpoint from the FDT: /media/mmcsd-1-0/
hub1: <Freescale EHCI root HUB, class 9/0, rev 2.00/1.00, addr 1> on usbus1
[ERL] Reading /media/mmcsd-1-0/grisp.ini
[ERL] Booting with arg: erl.rtems -C multi_time_warp -- -noshell -noinput -mode embedded -home . -pa . -root myapp -bindir myapp/erts-15.0.1/bin -boot myapp/releases/0.1.0/start -boot_var RELEASE_LIB myapp/lib  -config myapp/releases/0.1.0/sys.config -s elixir start_iex -extra --no-halt
[ERL] hostname: grisp-001159
[ERL] Setting up /etc from /media/mmcsd-1-0/etc
[ERL] Copying directory /media/mmcsd-1-0/etc to /etc
[ERL] Copying file /media/mmcsd-1-0/etc/dhcpcd.conf to /etc/dhcpcd.conf
[ERL] Copying file /media/mmcsd-1-0/etc/hosts to /etc/hosts
[ERL] Copying file /media/mmcsd-1-0/etc/resolv.conf to /etc/resolv.conf
[ERL] Starting DHCP
[ERL] mkdir /tmp
info: ffec0: link state changed to DOWN
[ERL] mkdir /tmp/log
[ERL] mkdir /home
[ERL] Setting environment
[ERL] chdir(/media/mmcsd-1-0/)
[ERL] getcwd: /media/mmcsd-1-0
[ERL] Starting BEAM
[ERL] No shell mode
uhub0: 1 port with 1 removable, self powered
uhub1: 1 port with 1 removable, self powered
ugen1.2: <Realtek 802.11n NIC> at usbus1
rtwn0: <Realtek 802.11n NIC, class 0/0, rev 2.00/0.00, addr 2> on usbus1
rtwn0: MAC/BB RTL8188EU, RF 6052 1T1R
warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell) or set the ELIXIR_ERL_OPTIONS="+fnu" environment variable
Error! elixir:start_iex/0 is not exported.

Runtime terminating during boot ({undef,[{elixir,start_iex,[],[]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done


fatal extension: source=5, is_internal=0, error=1
```

**Comment by ziopio** [comment]
I confirm that using elixir 1.16.3-otp-26 on Erlang 27.0.1 works and the iex prompt shows up.
This could mean that something changed in Elixir `1.17`

**Comment by Rashidwi** [comment]
Thanks so much for your support, greatly appreciated!

Thanks to your boot dump I was able to see that the line  _booting with arg:_ entry was completely wrong in my boot.
It appears that grisp.ini.mustache is highly sensitive to tabs and spaces. Once these were removed the reformatting of the args line then also caused problems. With that removed, and with elixir 1.16.3-otp-26 (or 1.16.2-otp-25) the boot is as follows:

[grispboot.txt](https://github.com/user-attachments/files/16996366/grispboot.txt)

So I'm back to the latin1 problem, but I notice the new output _matchstate term not allowed_ 

Any ideas?

S

**Comment by Rashidwi** [comment]
Success: finally have iex:> phew!

One change, which I thought I'd already done, in the read me, this is suggested:

>     def grisp do
>         [
>             otp: [verson: "27"],
>             deploy: [
>                 # pre_script: "rm -rf /Volumes/GRISP/*",
>                 # destination: "tmp/grisp"
>                 # post_script: "diskutil unmount /Volumes/GRISP",
>             ]
>         ]
>     end

Changing **_verson_** to **_version_**, seems to have removed the last problem, _matchstate term not allowed_. 

Could someone please update the readme!
This could close the  issue but for the latin1/utf-8

Sincere thanks for the support, I am delighted to finally have elixir running on my grisp2 :+1:

**Comment by ziopio** [comment]
Opened a new issue for the 1.17 problem with ` Error! elixir:start_iex/0 is not exported.` https://github.com/grisp/mix_grisp/issues/12
