### ISSUE TITLE
How to set sname and enable remsh 

### ISSUE THREAD

**Issue by Rashidwi** [grisp/mix_grisp#15]
Is there a way to invoke elixir with sname set, so I can remsh into it?

When booting erlang these are set as boot parameters, but I can see no 'correct' place to set sname

node() returns  :nonode@nohost, Node.isalive? returns false. 

Yet the hostname is specified in grisp.ini.mustache, and doesn't appear to be picked up by Node

**Comment by ziopio** [comment]
Addressed in https://github.com/grisp/mix_grisp/pull/16
